meta_product_name: "easy endo"
meta_title: "easy endo - Mieux vivre mon endométriose"
meta_description: "easy endo - Mieux vivre mon endométriose"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@compte_easy_endo"   # required for Twitter Cards
